import { PrismaClient } from '../src/generated/prisma'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  // Clean existing data
  await prisma.savedComparison.deleteMany()
  await prisma.savedCollege.deleteMany()
  await prisma.review.deleteMany()
  await prisma.course.deleteMany()
  await prisma.college.deleteMany()
  await prisma.user.deleteMany()

  // Demo user
  await prisma.user.create({
    data: {
      name: 'Manjeet Singh',
      email: 'demo@college.com',
      password: await hash('demo1234', 12),
    },
  })

  const colleges = [
    {
      name: 'Indian Institute of Technology Bombay',
      slug: 'iit-bombay',
      location: 'Mumbai, Maharashtra',
      city: 'Mumbai',
      state: 'Maharashtra',
      type: 'Government',
      rating: 4.8,
      totalFees: 900000,
      establishedYear: 1958,
      description: 'IIT Bombay is one of the premier engineering institutions in India, known for cutting-edge research and top placements.',
      website: 'https://www.iitb.ac.in',
      placementAvg: 2200000,
      placementHighest: 25000000,
      placementPercent: 95,
      naacGrade: 'A++',
      nirfRank: 3,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'Indian Institute of Technology Delhi',
      slug: 'iit-delhi',
      location: 'New Delhi, Delhi',
      city: 'New Delhi',
      state: 'Delhi',
      type: 'Government',
      rating: 4.8,
      totalFees: 850000,
      establishedYear: 1961,
      description: 'IIT Delhi is a world-class institution located in the capital city, producing top engineers and entrepreneurs.',
      website: 'https://www.iitd.ac.in',
      placementAvg: 2100000,
      placementHighest: 22000000,
      placementPercent: 94,
      naacGrade: 'A++',
      nirfRank: 2,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'Indian Institute of Technology Madras',
      slug: 'iit-madras',
      location: 'Chennai, Tamil Nadu',
      city: 'Chennai',
      state: 'Tamil Nadu',
      type: 'Government',
      rating: 4.9,
      totalFees: 875000,
      establishedYear: 1959,
      description: 'Ranked #1 in India by NIRF, IIT Madras is a hub for innovation, research, and industry collaboration.',
      website: 'https://www.iitm.ac.in',
      placementAvg: 2400000,
      placementHighest: 28000000,
      placementPercent: 96,
      naacGrade: 'A++',
      nirfRank: 1,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'BITS Pilani',
      slug: 'bits-pilani',
      location: 'Pilani, Rajasthan',
      city: 'Pilani',
      state: 'Rajasthan',
      type: 'Deemed',
      rating: 4.6,
      totalFees: 2000000,
      establishedYear: 1964,
      description: 'BITS Pilani is one of India\'s top private technical universities with a strong alumni network in Silicon Valley.',
      website: 'https://www.bits-pilani.ac.in',
      placementAvg: 1800000,
      placementHighest: 18000000,
      placementPercent: 90,
      naacGrade: 'A',
      nirfRank: 27,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'National Institute of Technology Trichy',
      slug: 'nit-trichy',
      location: 'Tiruchirappalli, Tamil Nadu',
      city: 'Tiruchirappalli',
      state: 'Tamil Nadu',
      type: 'Government',
      rating: 4.5,
      totalFees: 600000,
      establishedYear: 1964,
      description: 'NIT Trichy is consistently ranked among top NITs with excellent placement records and research output.',
      website: 'https://www.nitt.edu',
      placementAvg: 1400000,
      placementHighest: 12000000,
      placementPercent: 88,
      naacGrade: 'A++',
      nirfRank: 9,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'Vellore Institute of Technology',
      slug: 'vit-vellore',
      location: 'Vellore, Tamil Nadu',
      city: 'Vellore',
      state: 'Tamil Nadu',
      type: 'Deemed',
      rating: 4.3,
      totalFees: 1800000,
      establishedYear: 1984,
      description: 'VIT Vellore is one of India\'s largest private universities known for its modern campus and industry connections.',
      website: 'https://www.vit.ac.in',
      placementAvg: 900000,
      placementHighest: 8000000,
      placementPercent: 82,
      naacGrade: 'A++',
      nirfRank: 11,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
    {
      name: 'Delhi Technological University',
      slug: 'dtu-delhi',
      location: 'New Delhi, Delhi',
      city: 'New Delhi',
      state: 'Delhi',
      type: 'Government',
      rating: 4.2,
      totalFees: 700000,
      establishedYear: 1941,
      description: 'DTU is a premier state university in Delhi offering top engineering programs with strong industry placements.',
      website: 'https://www.dtu.ac.in',
      placementAvg: 1200000,
      placementHighest: 10000000,
      placementPercent: 85,
      naacGrade: 'A',
      nirfRank: 36,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'SRM Institute of Science and Technology',
      slug: 'srm-chennai',
      location: 'Chennai, Tamil Nadu',
      city: 'Chennai',
      state: 'Tamil Nadu',
      type: 'Deemed',
      rating: 4.0,
      totalFees: 1600000,
      establishedYear: 1985,
      description: 'SRM is among India\'s top private universities with strong research programs and global university tie-ups.',
      website: 'https://www.srmist.edu.in',
      placementAvg: 750000,
      placementHighest: 6000000,
      placementPercent: 78,
      naacGrade: 'A++',
      nirfRank: 18,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'Manipal Institute of Technology',
      slug: 'mit-manipal',
      location: 'Manipal, Karnataka',
      city: 'Manipal',
      state: 'Karnataka',
      type: 'Deemed',
      rating: 4.2,
      totalFees: 1900000,
      establishedYear: 1957,
      description: 'MIT Manipal is known for its international exposure, vibrant campus life, and strong alumni in global tech companies.',
      website: 'https://www.manipal.edu',
      placementAvg: 950000,
      placementHighest: 7500000,
      placementPercent: 80,
      naacGrade: 'A++',
      nirfRank: 22,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'PSG College of Technology',
      slug: 'psg-coimbatore',
      location: 'Coimbatore, Tamil Nadu',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      type: 'Private',
      rating: 4.3,
      totalFees: 500000,
      establishedYear: 1951,
      description: 'PSG Tech is a top autonomous engineering college in Tamil Nadu with strong industry linkages in Coimbatore.',
      website: 'https://www.psgtech.edu',
      placementAvg: 800000,
      placementHighest: 5000000,
      placementPercent: 84,
      naacGrade: 'A',
      nirfRank: 55,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'Thapar Institute of Engineering',
      slug: 'thapar-patiala',
      location: 'Patiala, Punjab',
      city: 'Patiala',
      state: 'Punjab',
      type: 'Deemed',
      rating: 4.2,
      totalFees: 1700000,
      establishedYear: 1956,
      description: 'Thapar is a top-ranked private institute in North India with excellent research facilities and placement record.',
      website: 'https://www.thapar.edu',
      placementAvg: 1100000,
      placementHighest: 9000000,
      placementPercent: 83,
      naacGrade: 'A',
      nirfRank: 31,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'Jadavpur University',
      slug: 'jadavpur-kolkata',
      location: 'Kolkata, West Bengal',
      city: 'Kolkata',
      state: 'West Bengal',
      type: 'Government',
      rating: 4.4,
      totalFees: 400000,
      establishedYear: 1955,
      description: 'Jadavpur University is one of the finest technical universities in East India with strong research output.',
      website: 'https://www.jaduniv.edu.in',
      placementAvg: 1000000,
      placementHighest: 9500000,
      placementPercent: 82,
      naacGrade: 'A++',
      nirfRank: 12,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
    {
      name: 'Amity University Noida',
      slug: 'amity-noida',
      location: 'Noida, Uttar Pradesh',
      city: 'Noida',
      state: 'Uttar Pradesh',
      type: 'Private',
      rating: 3.9,
      totalFees: 1500000,
      establishedYear: 2005,
      description: 'Amity is one of India\'s largest private universities with diverse programs and strong international collaborations.',
      website: 'https://www.amity.edu',
      placementAvg: 650000,
      placementHighest: 4500000,
      placementPercent: 72,
      naacGrade: 'A+',
      nirfRank: 72,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'IIT Kharagpur',
      slug: 'iit-kharagpur',
      location: 'Kharagpur, West Bengal',
      city: 'Kharagpur',
      state: 'West Bengal',
      type: 'Government',
      rating: 4.7,
      totalFees: 880000,
      establishedYear: 1951,
      description: 'The oldest IIT in India, IIT Kharagpur is known for its vast campus, diverse programs, and legendary alumni.',
      website: 'https://www.iitkgp.ac.in',
      placementAvg: 2000000,
      placementHighest: 20000000,
      placementPercent: 93,
      naacGrade: 'A++',
      nirfRank: 5,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'Chandigarh University',
      slug: 'chandigarh-university',
      location: 'Mohali, Punjab',
      city: 'Mohali',
      state: 'Punjab',
      type: 'Private',
      rating: 4.1,
      totalFees: 1200000,
      establishedYear: 2012,
      description: 'Chandigarh University is a fast-growing private university with modern facilities and strong industry partnerships.',
      website: 'https://www.cuchd.in',
      placementAvg: 700000,
      placementHighest: 5500000,
      placementPercent: 76,
      naacGrade: 'A+',
      nirfRank: 41,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'NIT Warangal',
      slug: 'nit-warangal',
      location: 'Warangal, Telangana',
      city: 'Warangal',
      state: 'Telangana',
      type: 'Government',
      rating: 4.4,
      totalFees: 580000,
      establishedYear: 1959,
      description: 'NIT Warangal is among the top NITs in India with excellent placement records and strong technical programs.',
      website: 'https://www.nitw.ac.in',
      placementAvg: 1300000,
      placementHighest: 11000000,
      placementPercent: 87,
      naacGrade: 'A++',
      nirfRank: 8,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'Lovely Professional University',
      slug: 'lpu-jalandhar',
      location: 'Phagwara, Punjab',
      city: 'Phagwara',
      state: 'Punjab',
      type: 'Private',
      rating: 3.8,
      totalFees: 1100000,
      establishedYear: 2005,
      description: 'LPU is one of India\'s largest private universities offering over 200 programs with a vibrant student community.',
      website: 'https://www.lpu.in',
      placementAvg: 500000,
      placementHighest: 4000000,
      placementPercent: 68,
      naacGrade: 'A+',
      nirfRank: 62,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'IIT Roorkee',
      slug: 'iit-roorkee',
      location: 'Roorkee, Uttarakhand',
      city: 'Roorkee',
      state: 'Uttarakhand',
      type: 'Government',
      rating: 4.7,
      totalFees: 860000,
      establishedYear: 1847,
      description: 'The oldest technical institution in Asia, IIT Roorkee combines heritage with modern research excellence.',
      website: 'https://www.iitr.ac.in',
      placementAvg: 1900000,
      placementHighest: 19000000,
      placementPercent: 92,
      naacGrade: 'A++',
      nirfRank: 6,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
    {
      name: 'Coimbatore Institute of Technology',
      slug: 'cit-coimbatore',
      location: 'Coimbatore, Tamil Nadu',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      type: 'Government',
      rating: 4.1,
      totalFees: 350000,
      establishedYear: 1956,
      description: 'CIT Coimbatore is a government autonomous institution with strong industry linkages in the manufacturing belt.',
      website: 'https://www.cit.edu.in',
      placementAvg: 600000,
      placementHighest: 4000000,
      placementPercent: 79,
      naacGrade: 'A',
      nirfRank: 95,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'Savitribai Phule Pune University',
      slug: 'sppu-pune',
      location: 'Pune, Maharashtra',
      city: 'Pune',
      state: 'Maharashtra',
      type: 'Government',
      rating: 4.0,
      totalFees: 300000,
      establishedYear: 1949,
      description: 'SPPU is one of the top affiliating universities in India, located in the thriving tech hub of Pune.',
      website: 'https://www.unipune.ac.in',
      placementAvg: 700000,
      placementHighest: 5000000,
      placementPercent: 75,
      naacGrade: 'A',
      nirfRank: 88,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'Nirma University',
      slug: 'nirma-ahmedabad',
      location: 'Ahmedabad, Gujarat',
      city: 'Ahmedabad',
      state: 'Gujarat',
      type: 'Deemed',
      rating: 4.2,
      totalFees: 1400000,
      establishedYear: 2003,
      description: 'Nirma University is a top-ranked institution in Gujarat with strong engineering and management programs.',
      website: 'https://www.nirmauni.ac.in',
      placementAvg: 900000,
      placementHighest: 7000000,
      placementPercent: 82,
      naacGrade: 'A',
      nirfRank: 51,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'IIIT Hyderabad',
      slug: 'iiit-hyderabad',
      location: 'Hyderabad, Telangana',
      city: 'Hyderabad',
      state: 'Telangana',
      type: 'Deemed',
      rating: 4.6,
      totalFees: 1600000,
      establishedYear: 1998,
      description: 'IIIT Hyderabad is a research-focused institution specializing in IT and CS with top global placements.',
      website: 'https://www.iiit.ac.in',
      placementAvg: 1700000,
      placementHighest: 15000000,
      placementPercent: 91,
      naacGrade: 'A',
      nirfRank: 32,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'Kalinga Institute of Industrial Technology',
      slug: 'kiit-bhubaneswar',
      location: 'Bhubaneswar, Odisha',
      city: 'Bhubaneswar',
      state: 'Odisha',
      type: 'Deemed',
      rating: 4.1,
      totalFees: 1300000,
      establishedYear: 1992,
      description: 'KIIT is a leading private university in East India known for its industry-oriented programs and placements.',
      website: 'https://www.kiit.ac.in',
      placementAvg: 750000,
      placementHighest: 6000000,
      placementPercent: 78,
      naacGrade: 'A++',
      nirfRank: 16,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'Anna University',
      slug: 'anna-university-chennai',
      location: 'Chennai, Tamil Nadu',
      city: 'Chennai',
      state: 'Tamil Nadu',
      type: 'Government',
      rating: 4.3,
      totalFees: 450000,
      establishedYear: 1978,
      description: 'Anna University is Tamil Nadu\'s premier technical university, affiliated with hundreds of colleges across the state.',
      website: 'https://www.annauniv.edu',
      placementAvg: 800000,
      placementHighest: 6500000,
      placementPercent: 80,
      naacGrade: 'A++',
      nirfRank: 14,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
    {
      name: 'Shiv Nadar University',
      slug: 'shiv-nadar-greater-noida',
      location: 'Greater Noida, Uttar Pradesh',
      city: 'Greater Noida',
      state: 'Uttar Pradesh',
      type: 'Private',
      rating: 4.4,
      totalFees: 2200000,
      establishedYear: 2011,
      description: 'Shiv Nadar University is a research-intensive private university with strong faculty and global outlook.',
      website: 'https://www.snu.edu.in',
      placementAvg: 1300000,
      placementHighest: 12000000,
      placementPercent: 85,
      naacGrade: 'A+',
      nirfRank: 28,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'IIT Kanpur',
      slug: 'iit-kanpur',
      location: 'Kanpur, Uttar Pradesh',
      city: 'Kanpur',
      state: 'Uttar Pradesh',
      type: 'Government',
      rating: 4.8,
      totalFees: 890000,
      establishedYear: 1959,
      description: 'IIT Kanpur is renowned for its academic rigour, entrepreneurship culture and path-breaking research.',
      website: 'https://www.iitk.ac.in',
      placementAvg: 2100000,
      placementHighest: 23000000,
      placementPercent: 94,
      naacGrade: 'A++',
      nirfRank: 4,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'Netaji Subhas University of Technology',
      slug: 'nsut-delhi',
      location: 'New Delhi, Delhi',
      city: 'New Delhi',
      state: 'Delhi',
      type: 'Government',
      rating: 4.1,
      totalFees: 680000,
      establishedYear: 1983,
      description: 'NSUT Delhi is a top Delhi government university known for strong placements in IT and core engineering.',
      website: 'https://www.nsut.ac.in',
      placementAvg: 1100000,
      placementHighest: 9000000,
      placementPercent: 83,
      naacGrade: 'A',
      nirfRank: 58,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'Symbiosis Institute of Technology',
      slug: 'sit-pune',
      location: 'Pune, Maharashtra',
      city: 'Pune',
      state: 'Maharashtra',
      type: 'Deemed',
      rating: 4.0,
      totalFees: 1600000,
      establishedYear: 2008,
      description: 'SIT Pune is part of the Symbiosis group with strong industry ties and a cosmopolitan student community.',
      website: 'https://www.sitpune.edu.in',
      placementAvg: 850000,
      placementHighest: 7000000,
      placementPercent: 79,
      naacGrade: 'A',
      nirfRank: 77,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'Ramaiah Institute of Technology',
      slug: 'rit-bangalore',
      location: 'Bengaluru, Karnataka',
      city: 'Bengaluru',
      state: 'Karnataka',
      type: 'Private',
      rating: 4.2,
      totalFees: 800000,
      establishedYear: 1962,
      description: 'RIT Bangalore is one of Karnataka\'s top private engineering colleges located in the Silicon Valley of India.',
      website: 'https://www.msrit.edu',
      placementAvg: 900000,
      placementHighest: 7500000,
      placementPercent: 82,
      naacGrade: 'A+',
      nirfRank: 68,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'BMS College of Engineering',
      slug: 'bmsce-bangalore',
      location: 'Bengaluru, Karnataka',
      city: 'Bengaluru',
      state: 'Karnataka',
      type: 'Private',
      rating: 4.1,
      totalFees: 750000,
      establishedYear: 1946,
      description: 'BMSCE is among Bangalore\'s oldest and most prestigious engineering colleges with a legacy of excellence.',
      website: 'https://www.bmsce.ac.in',
      placementAvg: 850000,
      placementHighest: 7000000,
      placementPercent: 80,
      naacGrade: 'A+',
      nirfRank: 74,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
    {
      name: 'IIT Guwahati',
      slug: 'iit-guwahati',
      location: 'Guwahati, Assam',
      city: 'Guwahati',
      state: 'Assam',
      type: 'Government',
      rating: 4.6,
      totalFees: 840000,
      establishedYear: 1994,
      description: 'IIT Guwahati is the gateway IIT of the Northeast with strong research programs and scenic campus.',
      website: 'https://www.iitg.ac.in',
      placementAvg: 1800000,
      placementHighest: 17000000,
      placementPercent: 91,
      naacGrade: 'A++',
      nirfRank: 7,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'PES University',
      slug: 'pes-bangalore',
      location: 'Bengaluru, Karnataka',
      city: 'Bengaluru',
      state: 'Karnataka',
      type: 'Deemed',
      rating: 4.2,
      totalFees: 1400000,
      establishedYear: 1972,
      description: 'PES University is a top private university in Bangalore known for its CS programs and startup ecosystem.',
      website: 'https://www.pes.edu',
      placementAvg: 950000,
      placementHighest: 8000000,
      placementPercent: 83,
      naacGrade: 'A+',
      nirfRank: 44,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'Institute of Chemical Technology Mumbai',
      slug: 'ict-mumbai',
      location: 'Mumbai, Maharashtra',
      city: 'Mumbai',
      state: 'Maharashtra',
      type: 'Deemed',
      rating: 4.5,
      totalFees: 550000,
      establishedYear: 1933,
      description: 'ICT Mumbai is Asia\'s premier chemical technology institution with legendary industry placements.',
      website: 'https://www.ictmumbai.edu.in',
      placementAvg: 1200000,
      placementHighest: 10000000,
      placementPercent: 89,
      naacGrade: 'A++',
      nirfRank: 19,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'Maharaja Sayajirao University of Baroda',
      slug: 'msu-baroda',
      location: 'Vadodara, Gujarat',
      city: 'Vadodara',
      state: 'Gujarat',
      type: 'Government',
      rating: 4.0,
      totalFees: 280000,
      establishedYear: 1949,
      description: 'MSU Baroda is a comprehensive state university with a rich academic tradition in science and arts.',
      website: 'https://www.msubaroda.ac.in',
      placementAvg: 600000,
      placementHighest: 4500000,
      placementPercent: 72,
      naacGrade: 'A++',
      nirfRank: 42,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'Graphic Era University',
      slug: 'graphic-era-dehradun',
      location: 'Dehradun, Uttarakhand',
      city: 'Dehradun',
      state: 'Uttarakhand',
      type: 'Deemed',
      rating: 3.9,
      totalFees: 1100000,
      establishedYear: 1993,
      description: 'Graphic Era is a fast-growing deemed university in Dehradun with strong technical and management programs.',
      website: 'https://www.geu.ac.in',
      placementAvg: 550000,
      placementHighest: 4000000,
      placementPercent: 70,
      naacGrade: 'A',
      nirfRank: 91,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'NIT Surathkal',
      slug: 'nit-surathkal',
      location: 'Mangalore, Karnataka',
      city: 'Mangalore',
      state: 'Karnataka',
      type: 'Government',
      rating: 4.4,
      totalFees: 590000,
      establishedYear: 1960,
      description: 'NIT Surathkal is a premier NIT on the coast of Karnataka with strong placements in IT and core sectors.',
      website: 'https://www.nitk.ac.in',
      placementAvg: 1250000,
      placementHighest: 11000000,
      placementPercent: 86,
      naacGrade: 'A++',
      nirfRank: 10,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
    {
      name: 'Koneru Lakshmaiah Education Foundation',
      slug: 'klef-vijayawada',
      location: 'Vijayawada, Andhra Pradesh',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      type: 'Deemed',
      rating: 4.0,
      totalFees: 1200000,
      establishedYear: 1980,
      description: 'KL University is a top private university in Andhra Pradesh known for its tech programs and placements.',
      website: 'https://www.kluniversity.in',
      placementAvg: 650000,
      placementHighest: 5000000,
      placementPercent: 76,
      naacGrade: 'A+',
      nirfRank: 53,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'Birla Institute of Technology Mesra',
      slug: 'bit-mesra',
      location: 'Ranchi, Jharkhand',
      city: 'Ranchi',
      state: 'Jharkhand',
      type: 'Deemed',
      rating: 4.1,
      totalFees: 1300000,
      establishedYear: 1955,
      description: 'BIT Mesra is a well-established deemed university in Jharkhand with strong engineering traditions.',
      website: 'https://www.bitmesra.ac.in',
      placementAvg: 700000,
      placementHighest: 5500000,
      placementPercent: 77,
      naacGrade: 'A',
      nirfRank: 61,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'NMIMS University',
      slug: 'nmims-mumbai',
      location: 'Mumbai, Maharashtra',
      city: 'Mumbai',
      state: 'Maharashtra',
      type: 'Deemed',
      rating: 4.3,
      totalFees: 2100000,
      establishedYear: 1981,
      description: 'NMIMS is a premium deemed university in Mumbai known for its MBA, engineering, and pharmacy programs.',
      website: 'https://www.nmims.edu',
      placementAvg: 1100000,
      placementHighest: 9000000,
      placementPercent: 84,
      naacGrade: 'A+',
      nirfRank: 34,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'IIT Hyderabad',
      slug: 'iit-hyderabad',
      location: 'Hyderabad, Telangana',
      city: 'Hyderabad',
      state: 'Telangana',
      type: 'Government',
      rating: 4.5,
      totalFees: 820000,
      establishedYear: 2008,
      description: 'IIT Hyderabad is a newer IIT that has quickly gained recognition for research and innovation.',
      website: 'https://www.iith.ac.in',
      placementAvg: 1700000,
      placementHighest: 16000000,
      placementPercent: 90,
      naacGrade: 'A++',
      nirfRank: 15,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'Vit University Chennai',
      slug: 'vit-chennai',
      location: 'Chennai, Tamil Nadu',
      city: 'Chennai',
      state: 'Tamil Nadu',
      type: 'Deemed',
      rating: 4.1,
      totalFees: 1750000,
      establishedYear: 2010,
      description: 'VIT Chennai campus offers similar programs as Vellore campus in the heart of Chennai city.',
      website: 'https://www.vit.ac.in/chennai',
      placementAvg: 850000,
      placementHighest: 7000000,
      placementPercent: 80,
      naacGrade: 'A++',
      nirfRank: 13,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'Aligarh Muslim University',
      slug: 'amu-aligarh',
      location: 'Aligarh, Uttar Pradesh',
      city: 'Aligarh',
      state: 'Uttar Pradesh',
      type: 'Government',
      rating: 4.2,
      totalFees: 350000,
      establishedYear: 1875,
      description: 'AMU is one of India\'s oldest central universities with a rich legacy in education and research.',
      website: 'https://www.amu.ac.in',
      placementAvg: 700000,
      placementHighest: 5500000,
      placementPercent: 74,
      naacGrade: 'A+',
      nirfRank: 23,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
    {
      name: 'GH Raisoni College of Engineering',
      slug: 'ghrce-nagpur',
      location: 'Nagpur, Maharashtra',
      city: 'Nagpur',
      state: 'Maharashtra',
      type: 'Private',
      rating: 3.9,
      totalFees: 700000,
      establishedYear: 1996,
      description: 'GHRCE is a top private engineering college in Vidarbha region with strong technical programs.',
      website: 'https://www.raisoni.net',
      placementAvg: 550000,
      placementHighest: 4000000,
      placementPercent: 71,
      naacGrade: 'A+',
      nirfRank: 99,
      imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    },
    {
      name: 'Pune Institute of Computer Technology',
      slug: 'pict-pune',
      location: 'Pune, Maharashtra',
      city: 'Pune',
      state: 'Maharashtra',
      type: 'Private',
      rating: 4.3,
      totalFees: 600000,
      establishedYear: 1983,
      description: 'PICT Pune is a top autonomous engineering college in Pune known for its CS/IT programs and placements.',
      website: 'https://www.pict.edu',
      placementAvg: 1000000,
      placementHighest: 8500000,
      placementPercent: 86,
      naacGrade: 'A',
      nirfRank: 82,
      imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    },
    {
      name: 'Hyderabad Central University',
      slug: 'hcu-hyderabad',
      location: 'Hyderabad, Telangana',
      city: 'Hyderabad',
      state: 'Telangana',
      type: 'Government',
      rating: 4.3,
      totalFees: 200000,
      establishedYear: 1974,
      description: 'University of Hyderabad is a top central university known for science research and social science programs.',
      website: 'https://www.uohyd.ac.in',
      placementAvg: 750000,
      placementHighest: 6000000,
      placementPercent: 76,
      naacGrade: 'A++',
      nirfRank: 20,
      imageUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800',
    },
    {
      name: 'Bennett University',
      slug: 'bennett-greater-noida',
      location: 'Greater Noida, Uttar Pradesh',
      city: 'Greater Noida',
      state: 'Uttar Pradesh',
      type: 'Private',
      rating: 3.8,
      totalFees: 1800000,
      establishedYear: 2016,
      description: 'Bennett University is backed by Times of India Group with strong media, tech, and management programs.',
      website: 'https://www.bennett.edu.in',
      placementAvg: 650000,
      placementHighest: 5000000,
      placementPercent: 73,
      naacGrade: 'A',
      nirfRank: 86,
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    },
    {
      name: 'SVNIT Surat',
      slug: 'svnit-surat',
      location: 'Surat, Gujarat',
      city: 'Surat',
      state: 'Gujarat',
      type: 'Government',
      rating: 4.2,
      totalFees: 560000,
      establishedYear: 1961,
      description: 'SVNIT Surat is a top NIT in Gujarat with solid engineering programs and growing industry connections.',
      website: 'https://www.svnit.ac.in',
      placementAvg: 1050000,
      placementHighest: 8500000,
      placementPercent: 83,
      naacGrade: 'A+',
      nirfRank: 45,
      imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    },
    {
      name: 'Osmania University',
      slug: 'osmania-hyderabad',
      location: 'Hyderabad, Telangana',
      city: 'Hyderabad',
      state: 'Telangana',
      type: 'Government',
      rating: 4.0,
      totalFees: 180000,
      establishedYear: 1918,
      description: 'Osmania University is one of the oldest universities in South India with a sprawling heritage campus.',
      website: 'https://www.osmania.ac.in',
      placementAvg: 550000,
      placementHighest: 4000000,
      placementPercent: 70,
      naacGrade: 'A+',
      nirfRank: 56,
      imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    },
  ]

  for (const college of colleges) {
    await prisma.college.create({
      data: {
        ...college,
        courses: {
          create: [
            { name: 'B.Tech Computer Science', duration: '4 Years', fees: Math.round(college.totalFees * 0.25), seats: 120 },
            { name: 'B.Tech Electronics', duration: '4 Years', fees: Math.round(college.totalFees * 0.24), seats: 90 },
            { name: 'B.Tech Mechanical', duration: '4 Years', fees: Math.round(college.totalFees * 0.23), seats: 90 },
            { name: 'M.Tech Computer Science', duration: '2 Years', fees: Math.round(college.totalFees * 0.15), seats: 40 },
            { name: 'MBA', duration: '2 Years', fees: Math.round(college.totalFees * 0.13), seats: 60 },
          ],
        },
        reviews: {
          create: [
            { author: 'Rahul Sharma', rating: 4.5, comment: 'Amazing faculty and infrastructure. Placements were excellent.', year: 2023 },
            { author: 'Priya Patel', rating: 4.0, comment: 'Great learning environment. Campus life is very active.', year: 2023 },
            { author: 'Arjun Mehta', rating: 5.0, comment: 'Best decision of my life. The alumni network is incredible.', year: 2022 },
          ],
        },
      },
    })
  }

  console.log('✅ Seeded 50 colleges with courses and reviews!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())